### ISSUE TITLE
Bloat

### ISSUE THREAD

**Issue by twojapiez** [ITKmind/custom#1]
Remove sound caches you absolute fucking moron

**Comment by melodyjkah** [comment]
no, remove everything. everything is bloat bro, remove all textures from tf2 and have fun!

**Comment by melodyjkah** [comment]
this repo is closed by kisak-valve.

**Comment by RandomTNT** [comment]
^^^

**Comment by melodyjkah** [comment]
@ITKmind twoj ociec to invalida

**Comment by twojapiez** [comment]
potwierdzam napierdalalem go mlotem
